#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit checks..."

echo "Running ESLint..."
npm run lint

echo "Running tests..."
npm run test

echo "Checking code coverage..."
npm run coverage:check

echo "All checks passed successfully!"
